[phases.setup]
nixPkgs = [
    "python3",
    "ffmpeg",
    "chromium",
    "glib",
    "nss",
    "nspr",
    "dbus",
    "atk",
    "cups",
    "libdrm",
    "gtk3",
    "pango",
    "cairo",
    "gdk-pixbuf",
    "xorg.libX11",
    "xorg.libXcomposite",
    "xorg.libXdamage",
    "xorg.libXfixes",
    "xorg.libXrandr",
    "mesa",
    "alsa-lib",
    "at-spi2-atk",
    "at-spi2-core"
]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python main.py"
